// Code generated by script/codegen-methods.bat; DO NOT EDIT.

export const rpc = {
  app: {
    hello: 1000001,
  },
  demo: {
    ping: 2000001,
    tick: 2000002,
  },
} as const;

const METHOD_NAMES = new Map<number, string>([
  [rpc.app.hello, 'app.hello'],
  [rpc.demo.ping, 'demo.ping'],
  [rpc.demo.tick, 'demo.tick'],
]);

export function methodName(method: number): string {
  return METHOD_NAMES.get(method) ?? String(method);
}
