import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(scriptDir, '..');
const registryPath = path.join(root, 'app', 'src', 'rpc', 'methods.json');
const serviceDir = path.join(root, 'service');
const goOutput = path.join(root, 'service', 'backend', 'methods_gen.go');
const tsOutput = path.join(root, 'app', 'src', 'rpc', 'methods_gen.ts');

function goIdent(name) {
  return name.slice(0, 1).toUpperCase() + name.slice(1);
}

function assertMethodName(name) {
  if (!/^[a-z][a-z0-9]*\.[a-z][a-z0-9]*$/.test(name)) {
    throw new Error(`Invalid RPC method name: ${name}`);
  }
}

function rangeKey(name) {
  return name.startsWith('app.') ? 'app' : 'default';
}

function getRange(registry, key) {
  const range = registry.ranges?.[key];
  if (!range) {
    throw new Error(`Missing RPC method range: ${key}`);
  }
  return range;
}

function main() {
  if (!fs.existsSync(registryPath)) {
    throw new Error(`RPC method registry not found: ${registryPath}`);
  }

  const registry = JSON.parse(fs.readFileSync(registryPath, 'utf8'));
  if (!registry.ranges) {
    throw new Error('RPC method registry is missing ranges.');
  }
  if (!registry.methods) {
    throw new Error('RPC method registry is missing methods.');
  }

  const methods = new Map();
  const ids = new Map();
  const pending = [];
  const entries = Object.entries(registry.methods).sort(([a], [b]) => a.localeCompare(b));
  if (entries.length === 0) {
    throw new Error('No RPC methods declared in app/src/rpc/methods.json.');
  }

  for (const [name, rawID] of entries) {
    assertMethodName(name);
    const id = Number(rawID);
    if (!Number.isInteger(id) || id < 0) {
      throw new Error(`Invalid RPC method id for ${name}: ${rawID}`);
    }
    if (id === 0) {
      pending.push(name);
      continue;
    }

    const key = rangeKey(name);
    const range = getRange(registry, key);
    if (id < Number(range.start) || id > Number(range.end)) {
      throw new Error(`RPC method id ${id} for ${name} is outside range ${key} [${range.start}, ${range.end}]`);
    }
    if (ids.has(id)) {
      throw new Error(`Duplicate RPC method id ${id} for ${name} and ${ids.get(id)}`);
    }

    methods.set(name, id);
    ids.set(id, name);
  }

  const nextByRange = new Map();
  for (const [key, range] of Object.entries(registry.ranges)) {
    const start = Number(range.start);
    const end = Number(range.end);
    let next = Number(range.next);
    if (start <= 0 || end < start) {
      throw new Error(`Invalid RPC method range: ${key}`);
    }
    if (next < start) {
      next = start;
    }
    nextByRange.set(key, next);
  }

  for (const [name, id] of methods) {
    const key = rangeKey(name);
    const next = nextByRange.get(key);
    if (id >= next) {
      nextByRange.set(key, id + 1);
    }
  }

  for (const name of pending.sort()) {
    const key = rangeKey(name);
    const range = getRange(registry, key);
    let next = nextByRange.get(key);
    while (ids.has(next)) {
      next += 1;
    }
    if (next > Number(range.end)) {
      throw new Error(`RPC method range exhausted: ${key}`);
    }
    methods.set(name, next);
    ids.set(next, name);
    nextByRange.set(key, next + 1);
  }

  for (const [key, next] of nextByRange) {
    registry.ranges[key].next = next;
  }

  const orderedMethods = {};
  for (const [name, id] of [...methods.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    orderedMethods[name] = id;
  }

  fs.writeFileSync(
    registryPath,
    `${JSON.stringify({ ranges: registry.ranges, methods: orderedMethods }, null, 2)}\n`,
    'utf8',
  );

  const sortedMethods = [...methods.entries()].sort((a, b) => a[1] - b[1] || a[0].localeCompare(b[0]));
  const namespaces = new Map();
  for (const [name, id] of [...sortedMethods].sort(([a], [b]) => a.localeCompare(b))) {
    const [namespace, action] = name.split('.');
    if (!namespaces.has(namespace)) {
      namespaces.set(namespace, []);
    }
    namespaces.get(namespace).push({
      name,
      goNamespace: goIdent(namespace),
      goField: goIdent(action),
      tsNamespace: namespace,
      tsAction: action,
      id,
    });
  }

  const goLines = [
    '// Code generated by script/codegen-methods.bat; DO NOT EDIT.',
    '',
    'package backend',
    '',
    'import "strconv"',
    '',
    'type Method int',
    '',
  ];
  for (const [, items] of namespaces) {
    items.sort((a, b) => a.goField.localeCompare(b.goField));
    goLines.push(`var ${items[0].goNamespace} = struct {`);
    for (const item of items) {
      goLines.push(`\t${item.goField} Method`);
    }
    goLines.push('}{');
    for (const item of items) {
      goLines.push(`\t${item.goField}: ${item.id},`);
    }
    goLines.push('}', '');
  }
  goLines.push('func MethodName(method Method) string {', '\tswitch method {');
  for (const [name] of sortedMethods) {
    const [namespace, action] = name.split('.');
    goLines.push(`\tcase ${goIdent(namespace)}.${goIdent(action)}:`, `\t\treturn "${name}"`);
  }
  goLines.push('\tdefault:', '\t\treturn strconv.Itoa(int(method))', '\t}', '}', '');
  fs.writeFileSync(goOutput, goLines.join('\n'), 'utf8');

  const tsLines = ['// Code generated by script/codegen-methods.bat; DO NOT EDIT.', '', 'export const rpc = {'];
  for (const [namespace, items] of namespaces) {
    tsLines.push(`  ${namespace}: {`);
    for (const item of items.sort((a, b) => a.tsAction.localeCompare(b.tsAction))) {
      tsLines.push(`    ${item.tsAction}: ${item.id},`);
    }
    tsLines.push('  },');
  }
  tsLines.push('} as const;', '', 'const METHOD_NAMES = new Map<number, string>([');
  for (const [name] of sortedMethods) {
    const [namespace, action] = name.split('.');
    tsLines.push(`  [rpc.${namespace}.${action}, '${name}'],`);
  }
  tsLines.push(']);', '', 'export function methodName(method: number): string {', '  return METHOD_NAMES.get(method) ?? String(method);', '}', '');
  fs.writeFileSync(tsOutput, tsLines.join('\n'), 'utf8');

  execFileSync('gofmt', ['-w', path.join('backend', 'methods_gen.go')], {
    cwd: serviceDir,
    stdio: 'inherit',
  });

  console.log(`Generated RPC methods: ${sortedMethods.length}`);
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
}
