// Code generated by script/codegen-methods.bat; DO NOT EDIT.

package backend

import "strconv"

type Method int

var App = struct {
	Hello Method
}{
	Hello: 1000001,
}

var Demo = struct {
	Ping Method
	Tick Method
}{
	Ping: 2000001,
	Tick: 2000002,
}

func MethodName(method Method) string {
	switch method {
	case App.Hello:
		return "app.hello"
	case Demo.Ping:
		return "demo.ping"
	case Demo.Tick:
		return "demo.tick"
	default:
		return strconv.Itoa(int(method))
	}
}
